"""The resolved config record every generated project writes.

Every generation pass writes the fully-resolved
:class:`~ignition_stack.config.schema.ProjectConfig` to
``.ignition-stack/config.json``. That file is the only artifact
``ignition-stack create`` needs to recreate or clone the stack:

    ignition-stack create <name> -f .ignition-stack/config.json

The positional name overrides the recorded one, so the same file clones
a stack under a new name. Editing the file before re-running is a
supported workflow - it is the same YAML/JSON schema that ``--dry-run``
dumps and ``-f`` rebuilds from.
"""

from __future__ import annotations

from pathlib import Path

from ignition_stack.config.io import ConfigIOError, dump_config, load_config
from ignition_stack.config.schema import ProjectConfig

# The directory the record lives in, at the project root. Dot-prefixed so it
# stays out of the way of the hand-readable compose/.env/Makefile tree.
RECORD_DIR = ".ignition-stack"
RECORD_NAME = "config.json"


class RecordError(Exception):
    """Raised when a project's config record can't be found or read."""


def record_path(project_dir: Path) -> Path:
    """Where the recorded config lives for a project rooted at ``project_dir``."""
    return Path(project_dir) / RECORD_DIR / RECORD_NAME


def has_record(project_dir: Path) -> bool:
    """True when ``project_dir`` carries a config record."""
    return record_path(project_dir).is_file()


def write_record(config: ProjectConfig, project_dir: Path) -> Path:
    """Persist ``config`` as the project's recorded config. Returns its path.

    The record is the *resolved* config as JSON (the caller passes the same
    object it handed to the writer); :func:`read_record` reproduces it exactly.
    """
    dst = record_path(project_dir)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_bytes(dump_config(config, "json").encode("utf-8"))
    return dst


def read_record(project_dir: Path) -> ProjectConfig:
    """Load the recorded config for a project.

    Raises :class:`RecordError` when the project has no record (a directory
    that was never generated by this CLI, or one whose record was removed) or
    when the record can't be parsed or validated.
    """
    src = record_path(project_dir)
    if not src.is_file():
        raise RecordError(f"no config record at {src}. This directory was not generated by " "ignition-stack (or its record was removed).")
    try:
        return load_config(src)
    except ConfigIOError as exc:
        raise RecordError(str(exc)) from exc
