"""SE-demo lifecycle record.

In SE-demo mode (``init --keep-cli``) the generated project keeps a copy of
its resolved :class:`~ignition_stack.config.schema.ProjectConfig` under
``.ignition-stack/config.json``. That record is the one primitive ``reset``
and ``switch-profile`` need: they read it back, optionally reshape it, and
re-run generation - no second trip through the wizard.

One-shot projects (the default) never write this directory, which is how
``reset`` tells the two modes apart: no record means the project deliberately
self-deleted its primitives and cannot be regenerated in place.
"""

from __future__ import annotations

from pathlib import Path

from ignition_stack.config.schema import ProjectConfig

# The directory the SE-demo primitives live in, at the project root. Dot-prefixed
# so it stays out of the way of the hand-readable compose/.env/Makefile tree.
LIFECYCLE_DIR = ".ignition-stack"
RECORD_NAME = "config.json"


class LifecycleError(Exception):
    """Raised when a lifecycle operation can't find or read its record."""


def record_path(project_dir: Path) -> Path:
    """Where the recorded config lives for a project rooted at ``project_dir``."""
    return Path(project_dir) / LIFECYCLE_DIR / RECORD_NAME


def has_record(project_dir: Path) -> bool:
    """True when ``project_dir`` is an SE-demo project (carries a record)."""
    return record_path(project_dir).is_file()


def write_record(config: ProjectConfig, project_dir: Path) -> Path:
    """Persist ``config`` as the project's recorded config. Returns its path.

    The JSON is what ``reset`` reads back, so it is the *resolved* config (the
    caller passes the same object it handed to the writer); pydantic's
    round-trip via :meth:`ProjectConfig.model_validate_json` reproduces it
    exactly.
    """
    dst = record_path(project_dir)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_bytes((config.model_dump_json(indent=2) + "\n").encode("utf-8"))
    return dst


def read_record(project_dir: Path) -> ProjectConfig:
    """Load the recorded config for an SE-demo project.

    Raises :class:`LifecycleError` when the project has no record (a one-shot
    project, or a directory that was never generated by this CLI).
    """
    src = record_path(project_dir)
    if not src.is_file():
        raise LifecycleError(
            f"no lifecycle record at {src}. This looks like a one-shot project "
            "(generated without --keep-cli); reset/switch-profile need an "
            "SE-demo project."
        )
    return ProjectConfig.model_validate_json(src.read_text(encoding="utf-8"))
